import {PluginSpecification} from '@valtimo/plugin';
import {GraphMailPluginConfigurationComponent} from './components/graph-mail-configuration/graph-mail-configuration.component';
import {SendEmailConfigurationComponent} from './components/send-email-configuration/send-email-configuration.component';
import {GRAPH_MAIL_PLUGIN_LOGO_BASE64} from './assets/graph-mail-plugin-logo';

const graphMailPluginSpecification: PluginSpecification = {
  pluginId: 'entra',
  pluginConfigurationComponent: GraphMailPluginConfigurationComponent,
  pluginLogoBase64: GRAPH_MAIL_PLUGIN_LOGO_BASE64,
  functionConfigurationComponents: {
    'send-email': SendEmailConfigurationComponent,
  },
  pluginTranslations: {
    nl: {
      title: 'Microsoft Graph Mail',
      description: 'Verstuur e-mails via Microsoft Graph API met OAuth2',
      configurationTitle: 'Configuratienaam',
      'send-email': 'Verstuur e-mail',
      tenantId: 'Tenant ID',
      clientId: 'Client ID',
      clientSecret: 'Client Secret',
      testSenderMailbox: 'Afzender testmail (e-mailadres)',
      tenantIdInvalidFormat: 'Tenant ID moet een geldig UUID zijn (bijv. xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).',
      clientIdInvalidFormat: 'Client ID moet een geldig UUID zijn (bijv. xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).',
      clientSecretPlaceholder: '(ongewijzigd laten als leeg)',
      testMailTitle: 'Testmail versturen',
      testMailDescription: 'Verstuur een testmail met voorbeelddata (Pietje van Patje) om te valideren of de credentials werken en e-mail kan worden verstuurd via Microsoft Graph.',
      testMailSaveFirst: 'Sla de configuratie eerst op voordat je een testmail verstuurt.',
      invalidEmailAddress: 'Ongeldig e-mailadres',
      testRecipientLabel: 'Ontvanger e-mailadres',
      sending: 'Versturen…',
      sendTestMail: 'Verstuur testmail',
      connectionError: 'Verbindingsfout:',
      // Process link fields
      senderMailbox: 'Afzender e-mailadres (UPN)',
      recipients: 'Ontvangers (verplicht)',
      cc: 'CC-adressen (optioneel, komma-gescheiden)',
      bcc: 'BCC-adressen (optioneel, komma-gescheiden)',
      replyTo: 'Reply-To adressen (optioneel)',
      subject: 'Onderwerp',
      contentId: 'Mailinhoud (bestand-ID)',
      contentIdTooltip: 'UUID van het tijdelijk opgeslagen HTML-bestand. Gebruik pv:contentId om het ID uit een procesvariabele op te halen. Compatibel met de FreeMarker-documentplugin.',
      attachmentIds: 'Bijlagen (bestand-IDs, optioneel)',
      attachmentIdsTooltip: 'Komma-gescheiden lijst van UUID\'s van tijdelijk opgeslagen bijlagen. Gebruik pv:attachmentIds om de lijst uit een procesvariabele op te halen.',
      senderMailboxPlaceholder: 'bijv. noreply@gemeente.nl',
      testRecipientPlaceholder: 'bijv. beheerder@gemeente.nl',
      connectionErrorFallback: 'Verbindingsfout',
    },
    en: {
      title: 'Microsoft Graph Mail',
      description: 'Send emails via Microsoft Graph API using OAuth2',
      configurationTitle: 'Configuration name',
      'send-email': 'Send email',
      tenantId: 'Tenant ID',
      clientId: 'Client ID',
      clientSecret: 'Client Secret',
      testSenderMailbox: 'Test sender mailbox (email address)',
      tenantIdInvalidFormat: 'Tenant ID must be a valid UUID (e.g. xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).',
      clientIdInvalidFormat: 'Client ID must be a valid UUID (e.g. xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).',
      clientSecretPlaceholder: '(leave blank to keep unchanged)',
      testMailTitle: 'Send test email',
      testMailDescription: 'Send a test email with sample data (John Doe) to validate that the credentials work and email can be sent via Microsoft Graph.',
      testMailSaveFirst: 'Save the configuration first before sending a test email.',
      invalidEmailAddress: 'Invalid email address',
      testRecipientLabel: 'Recipient email address',
      sending: 'Sending…',
      sendTestMail: 'Send test email',
      connectionError: 'Connection error:',
      // Process link fields
      senderMailbox: 'Sender email address (UPN)',
      recipients: 'Recipients (required)',
      cc: 'CC addresses (optional, comma-separated)',
      bcc: 'BCC addresses (optional, comma-separated)',
      replyTo: 'Reply-To addresses (optional)',
      subject: 'Subject',
      contentId: 'Mail body (file ID)',
      contentIdTooltip: 'UUID of the temporarily stored HTML file. Use pv:contentId to resolve the ID from a process variable. Compatible with the FreeMarker document plugin.',
      attachmentIds: 'Attachments (file IDs, optional)',
      attachmentIdsTooltip: 'Comma-separated list of UUIDs of temporarily stored attachments. Use pv:attachmentIds to resolve the list from a process variable.',
      senderMailboxPlaceholder: 'e.g. noreply@organisation.gov',
      testRecipientPlaceholder: 'e.g. admin@organisation.gov',
      connectionErrorFallback: 'Connection error',
    },
  },
};

export {graphMailPluginSpecification};
